#!/usr/bin/env python
import optparse							# parser fuer die Kommandozeile
import sys								# fuer die Standard-Datenstroeme std::in, out, err
from collections import defaultdict		# erstellt Item falls nicht existent 

# zusaetzliche Befehl-Optionen in der Kommandozeile
optparser = optparse.OptionParser()
optparser.add_option("-d", "--data", dest="train", default="data/hansards", help="Data filename prefix (default=data)")
optparser.add_option("-e", "--english", dest="english", default="e", help="Suffix of English filename (default=e)")
optparser.add_option("-f", "--french", dest="french", default="f", help="Suffix of French filename (default=f)")
optparser.add_option("-t", "--threshold", dest="threshold", default=0.5, type="float", help="Threshold for aligning with Dice's coefficient (default=0.5)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=sys.maxint, type="int", help="Number of sentences to use for training and alignment")
(opts, _) = optparser.parse_args()
f_data = "%s.%s" % (opts.train, opts.french)
e_data = "%s.%s" % (opts.train, opts.english)

########################
# get Data
########################
# Es wird zwischen std::err und std::out unterschieden,
# da nur die Alignments in die Datei geschrieben werden sollen.
# Der Rest geht in den std::err Kanal.

sys.stderr.write("Training with Dice's coefficient...")
bitext = [[sentence.strip().split() for sentence in pair] for pair in zip(open(f_data), open(e_data))[:opts.num_sents]]
# bitext: [ [fr Woerter (Satz)]  [eng Woerter (Satz)] ], [...]

f_count = defaultdict(int)	# int = 0
e_count = defaultdict(int)
fe_count = defaultdict(int)

# n: zaehlt Saetze fr + eng (Satz) = 1
# f: fr Satz
# e: eng Satz
for (n, (f, e)) in enumerate(bitext):
  # Es wird Wort fuer Wort durch die Saetze gegangen
  # f_i: fr Woerter
  # e_j: eng Woerter
  # f_count: zaehlt Vorkommen von einzelnem f_i
  # e_count: zaehlt Vorkommen von einzelnem e_j
  # fe_count: zaehlt gemeinsame Vorkommen von einzelnem f_i und e_j
  for f_i in set(f):
    f_count[f_i] += 1
    for e_j in set(e):
      fe_count[(f_i,e_j)] += 1
  for e_j in set(e):
    e_count[e_j] += 1
  if n % 500 == 0:
    sys.stderr.write(".")

########################
# Formel
########################
dice = defaultdict(int)
for (k, (f_i, e_j)) in enumerate(fe_count.keys()):
  dice[(f_i,e_j)] = 2.0 * fe_count[(f_i, e_j)] / (f_count[f_i] + e_count[e_j])
  if k % 5000 == 0:
    sys.stderr.write(".")
sys.stderr.write("\n")

########################
# print
########################
for (f, e) in bitext:
  for (i, f_i) in enumerate(f): 
    for (j, e_j) in enumerate(e):
      if dice[(f_i,e_j)] >= opts.threshold:
        sys.stdout.write("%i-%i " % (i,j))
  sys.stdout.write("\n")
